name: Build and Publish Map Cache

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (branch or tag) to build"
        required: true
        default: "master"

jobs:
  build-and-push:
    name: Build Go Binary & Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important! Needed for full git history

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Extract build metadata
      - name: Get Git Metadata
        id: meta
        run: |
          echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

      # Step 5: Build and push multi-arch Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            goodblaster/map-cache:latest
            goodblaster/map-cache:${{ github.event.release.tag_name || github.event.inputs.ref || 'manual' }}
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT=${{ env.COMMIT }}
            DATE=${{ env.DATE }}
