name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: 'Docker tag to deploy (e.g. latest or v1.2.3)'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform
        uses: actions/checkout@v4
        with:
          repository: goodblaster/infra
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: infra

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init and Apply
        working-directory: infra
        run: |
          terraform init
          terraform apply -auto-approve -var="docker_image=goodblaster/map-cache:${{ github.event.inputs.docker_image_tag }}"
